# Generated by Django 5.1.15 on 2026-04-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user_verification_photo',
            field=models.ImageField(blank=True, null=True, upload_to='proofs/verify/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_verified',
            field=models.BooleanField(default=False),
        ),
    ]
